version: '2'
services:
  iki-robot-sim:
    image: rakeshfirstry:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      WAIT_FOR_ROSCORE: 0
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
      PATH: /usr/local/nvidia/bin:${PATH}
      LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
    privileged: true
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm

    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME/.Xauthority:/root/.Xauthority
      - $HOME/.gazebo:/root/.gazebo
      - nvidia_driver_384.130:/usr/local/nvidia:ro

    command: /bin/bash -c "
             tail -f /dev/null"


version: '2'
volumes:
  nvidia_driver_384.130:
    external: true

